function correct = get_transitions(TM, choice_trials, features)

    if features == 1
        for j = 1:size(choice_trials,1)
            if choice_trials(j,7) == 1
                if choice_trials(j,8) == 1
                    correct(j,1) = TM(choice_trials(j,1), choice_trials(j,3)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,4)) == 1 && ...
                                   TM(choice_trials(j,1), choice_trials(j,5)) == 0 && ...
                                   TM(choice_trials(j,2), choice_trials(j,6)) == 1;
                else
                    correct(j,1) = TM(choice_trials(j,1), choice_trials(j,3)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,4)) == 1 && ...
                                   TM(choice_trials(j,1), choice_trials(j,5)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,6)) == 0;

                end

            elseif choice_trials(j,7) == 2
                if choice_trials(j,8) == 1

                    correct(j,1) = TM(choice_trials(j,1), choice_trials(j,5)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,6)) == 1 && ...
                                   TM(choice_trials(j,1), choice_trials(j,3)) == 0 && ...
                                   TM(choice_trials(j,2), choice_trials(j,4)) == 1;

                else

                    correct(j,1) = TM(choice_trials(j,1), choice_trials(j,5)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,6)) == 1 && ...
                                   TM(choice_trials(j,1), choice_trials(j,3)) == 1 && ...
                                   TM(choice_trials(j,2), choice_trials(j,4)) == 0;
                end
            end
        end
    end
end

